### ISSUE TITLE
Error: TUI_CoD_LuaCall_QuadCache_GC+0x1C

### ISSUE THREAD

**Issue by shiversoftdev** [coxtristan/T7EditorClient#2] opened 2023-05-15 08:14 UTC
lua_panic: Unknown error occurred.
Stack traceback:
    [C]: in function 'lua_panic'
    [string "script.lua"]:23: in function 'calculate'
    [string "script.lua"]:47: in function 'main'
    [string "script.lua"]:56: in main chunk
    [C]: in ?
    
    lua_panic: Unknown error occurred.
Stack traceback:
    [C]: in function 'lua_panic'
    [string "script.lua"]:23: in function 'calculate'
    [string "helpers.lua"]:51: in function 'validateInput'
    [string "helpers.lua"]:84: in function 'processData'
    [string "script.lua"]:112: in function 'main'
    [string "script.lua"]:120: in main chunk
    [C]: in ?

lua_panic: Unknown error occurred.
Stack traceback:
    [C]: in function 'lua_panic'
    [string "script.lua"]:23: in function 'calculate'
    [string "helpers.lua"]:51: in function 'validateInput'
    [string "helpers.lua"]:84: in function 'processData'
    [string "helpers.lua"]:112: in function 'checkPermissions'
    [string "helpers.lua"]:146: in function 'parseData'
    [string "helpers.lua"]:178: in function 'filterData'
    [string "script.lua"]:224: in function 'main'
    [string "script.lua"]:238: in function 'execute'
    [string "script.lua"]:248: in function 'dispatch'
    [string "script.lua"]:275: in main chunk
    [C]: in ?

**Comment by nice-sprite** [comment] 2023-05-15 08:33
Working as intended. Closing this.

**Closed as completed by nice-sprite** 2023-05-15 08:33 UTC
